#!/usr/bin/env python3
"""
Generate proper calibration data for Lightning UNet quantization.

Key fix: calibration latents must be scaled by init_noise_sigma (14.6x)
to match actual inference distribution. Original calibration NPZ used
std=1.0 latents, but EulerDiscrete scheduler scales them by ~14.6.

By default this keeps the historical W8A16-friendly behavior. For int8 lab
experiments you can optionally feed a prompt JSON (for example the checkpoint-
aligned anime prompt set generated by ``generate_calibration_prompts.py``)
without touching the default pipeline.

Usage:
    python NPU/make_lightning_calibration.py --samples 16
    python NPU/make_lightning_calibration.py --samples 4 --prompts-json SDXL/калибровка.json
"""
import argparse, gc, json, sys
from pathlib import Path
import numpy as np
import torch

ROOT = Path(__file__).resolve().parent.parent
SDXL_NPU = ROOT / "sdxl_npu"
if str(SDXL_NPU) not in sys.path:
    sys.path.insert(0, str(SDXL_NPU))

from export_sdxl_to_onnx import (
    collect_unet_resnet_conditioning_modules,
    compute_external_resnet_biases,
    infer_unet_resnet_spatial_shapes,
)


DEFAULT_PROMPTS = [
    "1girl, upper body, looking at viewer, masterpiece, best quality",
    "landscape, mountains, sunset, dramatic lighting, 4k",
    "a cute cat sitting on a windowsill, digital art",
    "abstract art, colorful geometric shapes, modern",
    "portrait of an old man, oil painting, rembrandt style",
    "city skyline at night, neon lights, cyberpunk",
    "a red sports car on a highway, motion blur",
    "underwater scene, coral reef, tropical fish",
    "a castle on a hill, medieval fantasy, detailed",
    "anime girl with blue hair, school uniform",
    "still life, flowers in a vase, soft lighting",
    "robot standing in rain, futuristic, cinematic",
    "forest path, autumn leaves, golden hour",
    "spacecraft orbiting a planet, sci-fi illustration",
    "a dog playing in the snow, happy expression",
    "dark gothic cathedral interior, stained glass",
    "beach scene, waves crashing, tropical paradise",
    "steampunk clockwork mechanism, brass and copper",
    "fantasy dragon flying over mountains, epic",
    "cozy cafe interior, warm lighting, detailed",
]


def _device_from_arg(device_arg: str) -> torch.device:
    if device_arg == "auto":
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")
    return torch.device(device_arg)


def _weight_dtype_for_device(device: torch.device) -> torch.dtype:
    return torch.float16 if device.type == "cuda" else torch.float32


def _cleanup_torch() -> None:
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()


def _build_add_time_ids(height: int, width: int, device: torch.device) -> torch.Tensor:
    return torch.tensor(
        [[height, width, 0, 0, height, width]],
        dtype=torch.float32,
        device=device,
    )


def _load_lightning_scheduler(diffusers_dir: Path, device: torch.device):
    from diffusers import EulerDiscreteScheduler

    scheduler_cfg = json.loads((diffusers_dir / "scheduler" / "scheduler_config.json").read_text())
    scheduler = EulerDiscreteScheduler.from_config(scheduler_cfg, timestep_spacing="trailing")
    scheduler.set_timesteps(8, device=device)
    return scheduler


def _encode_prompts_staged(diffusers_dir: Path, prompts: list[str], device: torch.device) -> list[tuple[torch.Tensor, torch.Tensor]]:
    from transformers import CLIPTextModel, CLIPTextModelWithProjection, CLIPTokenizer

    weight_dtype = _weight_dtype_for_device(device)

    print(f"[stage] Loading text encoders on {device} ({weight_dtype})...")
    tok_l = CLIPTokenizer.from_pretrained(str(diffusers_dir / "tokenizer"), local_files_only=True)
    tok_g = CLIPTokenizer.from_pretrained(str(diffusers_dir / "tokenizer_2"), local_files_only=True)
    te_l = CLIPTextModel.from_pretrained(
        str(diffusers_dir / "text_encoder"),
        torch_dtype=weight_dtype,
        local_files_only=True,
    ).to(device).eval()
    te_g = CLIPTextModelWithProjection.from_pretrained(
        str(diffusers_dir / "text_encoder_2"),
        torch_dtype=weight_dtype,
        local_files_only=True,
    ).to(device).eval()

    prompt_cache: list[tuple[torch.Tensor, torch.Tensor]] = []
    with torch.no_grad():
        for prompt_idx, prompt in enumerate(prompts):
            ids_l = tok_l(
                prompt,
                padding="max_length",
                max_length=77,
                truncation=True,
                return_tensors="pt",
            ).input_ids.to(device)
            ids_g = tok_g(
                prompt,
                padding="max_length",
                max_length=77,
                truncation=True,
                return_tensors="pt",
            ).input_ids.to(device)

            out_l = te_l(ids_l, output_hidden_states=True)
            out_g = te_g(ids_g, output_hidden_states=True)

            prompt_embeds = torch.cat([out_l.hidden_states[-2], out_g.hidden_states[-2]], dim=-1)
            pooled_prompt_embeds = out_g.text_embeds
            prompt_cache.append(
                (
                    prompt_embeds.detach().cpu().float(),
                    pooled_prompt_embeds.detach().cpu().float(),
                )
            )

            if (prompt_idx + 1) % 10 == 0 or (prompt_idx + 1) == len(prompts):
                print(f"  [prompt-encode] {prompt_idx + 1}/{len(prompts)}", flush=True)

    del te_l, te_g, tok_l, tok_g
    _cleanup_torch()
    print(f"[stage] Prompt cache ready: {len(prompt_cache)} prompts stored on CPU")
    return prompt_cache


def _load_prompts(prompts_json: Path | None, prompt_limit: int | None) -> list[str]:
    if prompts_json is None:
        prompts = list(DEFAULT_PROMPTS)
    else:
        data = json.loads(prompts_json.read_text(encoding="utf-8"))
        raw_prompts = data.get("prompts", data)
        prompts = []
        for entry in raw_prompts:
            if isinstance(entry, str):
                text = entry.strip()
            elif isinstance(entry, dict):
                text = str(entry.get("positive", "")).strip()
            else:
                text = ""
            if text:
                prompts.append(text)
        if not prompts:
            raise ValueError(f"No usable prompts found in {prompts_json}")

    if prompt_limit is not None:
        prompts = prompts[:prompt_limit]
    return prompts


def _build_sample_plan(samples: int, prompts: list[str], timesteps, sampling_order: str) -> list[tuple[int, float, int]]:
    if sampling_order == "legacy":
        plan = []
        sample_idx = 0
        for prompt_idx in range(len(prompts)):
            for timestep_idx, timestep in enumerate(timesteps):
                plan.append((prompt_idx, float(timestep), timestep_idx))
                sample_idx += 1
                if sample_idx >= samples:
                    return plan
        return plan

    if sampling_order == "cyclic_diverse":
        plan = []
        num_timesteps = len(timesteps)
        for sample_idx in range(samples):
            prompt_idx = sample_idx % len(prompts)
            timestep_idx = sample_idx % num_timesteps
            plan.append((prompt_idx, float(timesteps[timestep_idx]), timestep_idx))
        return plan

    raise ValueError(f"Unknown sampling_order: {sampling_order}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--samples", type=int, default=16, help="Number of calibration samples")
    ap.add_argument("--out-dir", type=str, default=None)
    ap.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    ap.add_argument(
        "--memory-mode",
        choices=["legacy", "staged"],
        default="legacy",
        help="legacy keeps the historical full-pipeline behavior; staged loads text encoders and UNet in separate phases to reduce peak RAM/VRAM.",
    )
    ap.add_argument(
        "--text-encoder-device",
        type=str,
        default="auto",
        help="Device for staged text encoding phase (default: follow --device / best available)",
    )
    ap.add_argument(
        "--unet-device",
        type=str,
        default="auto",
        help="Device for staged Lightning UNet bias phase (default: follow --device / best available)",
    )
    ap.add_argument("--diffusers-dir", type=str, default=str(SDXL_NPU / "diffusers_pipeline"))
    ap.add_argument("--merged-unet-dir", type=str, default=str(SDXL_NPU / "unet_lightning8step_merged"))
    ap.add_argument("--prompts-json", type=str, default=None,
                    help="Optional JSON with prompt entries (supports {'prompts': [{'positive': ...}]})")
    ap.add_argument("--prompt-limit", type=int, default=None,
                    help="Optional cap on unique prompts loaded from --prompts-json")
    ap.add_argument("--sampling-order", choices=["legacy", "cyclic_diverse"], default="legacy",
                    help="Sample ordering strategy. legacy preserves the historical prompt-first order; cyclic_diverse spreads small sample counts across more prompts.")
    args = ap.parse_args()

    legacy_device = _device_from_arg(args.device)
    text_device = legacy_device if args.text_encoder_device == "auto" else _device_from_arg(args.text_encoder_device)
    unet_device = legacy_device if args.unet_device == "auto" else _device_from_arg(args.unet_device)
    out_dir = Path(args.out_dir) if args.out_dir else SDXL_NPU / f"calib_lightning_w8a16_{args.samples}s_scaled"
    out_dir.mkdir(parents=True, exist_ok=True)
    diffusers_dir = Path(args.diffusers_dir)
    merged_unet_dir = Path(args.merged_unet_dir)
    prompts_json = Path(args.prompts_json) if args.prompts_json else None
    prompts = _load_prompts(prompts_json, args.prompt_limit)

    print(f"[config] samples={args.samples}, out={out_dir}, device={legacy_device}")
    print(f"[config] diffusers_dir={diffusers_dir}")
    print(f"[config] merged_unet_dir={merged_unet_dir}")
    print(f"[config] memory_mode={args.memory_mode}")
    if args.memory_mode == "staged":
        print(f"[config] text_encoder_device={text_device}")
        print(f"[config] unet_device={unet_device}")
    if prompts_json:
        print(f"[config] prompts_json={prompts_json} ({len(prompts)} prompts loaded)")
    else:
        print(f"[config] prompts=builtin ({len(prompts)} prompts)")
    print(f"[config] sampling_order={args.sampling_order}")

    from diffusers import StableDiffusionXLPipeline, EulerDiscreteScheduler, UNet2DConditionModel
    pipe = None
    prompt_cache: list[tuple[torch.Tensor, torch.Tensor]] | None = None

    if args.memory_mode == "legacy":
        print("[init] Loading pipeline...")
        pipe = StableDiffusionXLPipeline.from_pretrained(
            str(diffusers_dir),
            torch_dtype=_weight_dtype_for_device(legacy_device),
            local_files_only=True,
        ).to(legacy_device)
        pipe.scheduler = EulerDiscreteScheduler.from_config(
            pipe.scheduler.config, timestep_spacing="trailing"
        )
        pipe.scheduler.set_timesteps(8, device=legacy_device)
        scheduler = pipe.scheduler
    else:
        prompt_cache = _encode_prompts_staged(diffusers_dir, prompts, text_device)
        scheduler = _load_lightning_scheduler(diffusers_dir, unet_device)

    timesteps = scheduler.timesteps
    init_sigma = float(scheduler.init_noise_sigma)
    print(f"[scheduler] init_noise_sigma={init_sigma:.3f}, timesteps={timesteps.tolist()}")

    # Load Lightning UNet for bias computation
    target_unet_device = legacy_device if args.memory_mode == "legacy" else unet_device
    print(f"[init] Loading Lightning UNet on {target_unet_device}...")
    lightning_unet = UNet2DConditionModel.from_pretrained(
        str(merged_unet_dir),
        torch_dtype=torch.float32,
        local_files_only=True,
    ).to(target_unet_device)
    lightning_unet.eval()

    resnet_modules = collect_unet_resnet_conditioning_modules(lightning_unet)
    spatial_shapes = infer_unet_resnet_spatial_shapes(lightning_unet, 128, 128)
    bias_names = [
        f"resnet_bias_{i:02d}_{name.replace('.', '_')}"
        for i, (name, _) in enumerate(resnet_modules)
    ]
    print(f"[extmaps] {len(resnet_modules)} bias sites")

    input_list_lines = []
    sample_plan = _build_sample_plan(args.samples, prompts, timesteps.tolist(), args.sampling_order)

    for sample_idx, (prompt_idx, timestep_value, timestep_idx) in enumerate(sample_plan):
        prompt = prompts[prompt_idx]

        if args.memory_mode == "legacy":
            assert pipe is not None
            with torch.no_grad():
                pe, _, ppe, _ = pipe.encode_prompt(
                    prompt=prompt, negative_prompt="",
                    device=legacy_device, num_images_per_prompt=1,
                    do_classifier_free_guidance=False,
                )
            pe = pe.to(target_unet_device, dtype=torch.float32)
            ppe = ppe.to(target_unet_device, dtype=torch.float32)
            add_time_ids = pipe._get_add_time_ids(
                original_size=(1024, 1024),
                crops_coords_top_left=(0, 0),
                target_size=(1024, 1024),
                dtype=pe.dtype,
                text_encoder_projection_dim=1280,
            ).to(target_unet_device, dtype=torch.float32)
        else:
            assert prompt_cache is not None
            pe_cpu, ppe_cpu = prompt_cache[prompt_idx]
            pe = pe_cpu.to(target_unet_device, dtype=torch.float32)
            ppe = ppe_cpu.to(target_unet_device, dtype=torch.float32)
            add_time_ids = _build_add_time_ids(1024, 1024, target_unet_device)

        t = timesteps[timestep_idx]
        sample_dir = out_dir / f"sample_{sample_idx:04d}"
        sample_dir.mkdir(parents=True, exist_ok=True)

        # Create latent scaled by init_noise_sigma (matching real inference)
        gen = torch.Generator(device=target_unet_device).manual_seed(42 + sample_idx * 13 + timestep_idx * 7)
        latent = torch.randn((1, 4, 128, 128), generator=gen, device=target_unet_device, dtype=torch.float32)
        latent = latent * init_sigma  # CRITICAL: match actual inference scale

        # Scale model input for this timestep
        latent_in = scheduler.scale_model_input(latent, t)

        # Compute biases
        with torch.no_grad():
            bias_tensors = compute_external_resnet_biases(
                lightning_unet,
                latent_in.to(target_unet_device, dtype=torch.float32),
                torch.tensor([float(t)], dtype=torch.float32, device=target_unet_device),
                pe,
                ppe,
                add_time_ids,
            )

        # Save as NCHW float32 raw files
        # QNN converter IR always reads inputs as float32 (even for fp16 ONNX models)
        sample_np = latent_in.cpu().float().numpy()  # [1,4,128,128] NCHW float32
        sample_np.tofile(str(sample_dir / "sample.raw"))

        ehs_np = pe.cpu().float().numpy()  # [1,77,2048] float32
        ehs_np.tofile(str(sample_dir / "encoder_hidden_states.raw"))

        file_parts = [
            str(sample_dir / "sample.raw"),
            str(sample_dir / "encoder_hidden_states.raw"),
        ]

        for bi, ((name, _), bt) in enumerate(zip(resnet_modules, bias_tensors)):
            h, w = spatial_shapes[name]
            bias_expanded = bt.expand(-1, -1, h, w).cpu().float().numpy()  # NCHW float32
            fname = f"{bias_names[bi]}.raw"
            bias_expanded.tofile(str(sample_dir / fname))
            file_parts.append(str(sample_dir / fname))

        input_list_lines.append(" ".join(file_parts))

        print(f"  [{sample_idx+1}/{args.samples}] prompt={prompt_idx}, t={timestep_value:.0f}, "
              f"latent_range=[{sample_np.min():.2f}, {sample_np.max():.2f}]")

    # Write input list
    input_list_path = out_dir / "unet_extbias_input_list.txt"
    with open(input_list_path, "w") as f:
        f.write("\n".join(input_list_lines) + "\n")

    del lightning_unet
    if pipe is not None:
        del pipe
    _cleanup_torch()

    print(f"\n[done] {len(sample_plan)} samples, input list: {input_list_path}")
    print(f"  Latent scaling: init_noise_sigma={init_sigma:.3f}")


if __name__ == "__main__":
    main()
